---
- name: Configure storm.yaml
  template: dest="{{storm_root_dir}}/apache-storm-{{storm_version}}/conf/storm.yaml" owner={{storm_user}} group={{storm_group}} mode=644 src=storm.yaml.j2
  notify:
    - Restart Nimbus
    - Restart UI

- name: Setup Storm nimbus upstart script
  copy: dest={{nimbus_upstart_conf}} owner=root group=root mode=644 src=storm-nimbus.conf
  notify:
    - Restart Nimbus
  when: not use_systemd

- name: Setup Storm nimbus systemd script
  copy: dest={{nimbus_systemd_service}} owner=root group=root mode=644 src=storm-nimbus.service
  notify:
    - Restart Nimbus
  when: use_systemd

- name: Setup Storm UI upstart script
  copy: dest={{stormui_upstart_conf}} owner=root group=root mode=644 src=storm-ui.conf
  notify:
    - Restart UI
  when: storm_ui_enabled and not use_systemd

- name: Setup Storm UI systemd script
  copy: dest={{stormui_systemd_service}} owner=root group=root mode=644 src=storm-ui.service
  notify:
    - Restart UI
  when: storm_ui_enabled and use_systemd

- command: systemctl daemon-reload
  when: use_systemd

- meta: flush_handlers
