---
- name: Enable and Start Storm Supervisor
  service: name=storm-supervisor state=started enabled=yes

- name: Enable and Start Storm Logviewer
  service: name=storm-logviewer state=started enabled=yes
